server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: 1212
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
app:
  jwt:
    secret: replace_with_long_secret
    expiration-ms: 3600000