server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
app:
  jwt:
    secret: replace_with_long_secret
    expiration-ms: 3600000


  messages:
    basename: messages
    encoding: UTF-8
    use-code-as-default-message: true